### ISSUE TITLE
General wondering

### ISSUE THREAD

**Issue by Skripkon** [setday/EVatization#1]
What is this project all about?
How to run it locally?

**Comment by setday** [comment]
Hi there! 👋

There is no special purpose for this project. It just made for fun) 😇

You can use online version of this project, if you want to see, what this app can make: https://setday.github.io/EVatization/.

If you want it to run locally, just use the following commands:
``` bash
npm i
npm run preview
```

PS: don't forget to clone the project first.

**Comment by Skripkon** [comment]
Thank you! I found the error! I forgot to clone the project before running it locally!!!
